name: Manual Compile Workflow
on:
  pull_request:
    branches: [ main, next ]
  workflow_dispatch:
jobs:
  compile:
    name: Compile Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.13'
    - name: Update
      run: sudo apt update
    - name: Install apt dependencies
      run: sudo apt install -y build-essential libcap-dev libfmt-dev libdrm-dev git python3-sphinx libyaml-dev python3-yaml python3-ply python3-jinja2 libgnutls28-dev openssl libboost-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies for testing
      run: |
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Cache libcamera
      id: cache-libcamera
      uses: actions/cache@v3
      with:
        path: /home/runner/work/libcamera
        key: ${{ runner.os }}-libcamera
    - name: Generate libcamera
      if: steps.cache-libcamera.outputs.cache-hit != 'true'
      run: cd /home/runner/work; git clone https://github.com/raspberrypi/libcamera.git; cd libcamera; meson build; ninja -C build
