name: flake8

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Update
      run: sudo apt update
    - name: Install apt dependencies
      run: sudo apt install -y python3-dev libpython3-dev build-essential libcap-dev ninja-build libfmt-dev libdrm-dev git
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies for testing
      run: |
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: kmsxx
      run: cd /home/runner/work; git clone https://github.com/tomba/kmsxx.git; cd kmsxx; meson build; ninja -C build
    - name: set pythonpath
      run: |
        echo "PYTHONPATH=.:/home/runner/work/kmsxx/build/py/" >> $GITHUB_ENV
    - name: test cv2
      run: python -c 'import cv2; print(cv2.__version__)'
    - name: test pykms
      run: python -c 'import pykms'
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
